// Generated by sembla-cuda 0.3.0. DO NOT EDIT.
// model-name-sha256: 502d6d87499e2c0a21cf3efe27c4fe6ffbd657956a7d9fedc66f29cb5ef68623

// No result-bearing atomics are used. Effects are staged in generated
// rule/effect/row order, then scattered by ascending destination cell.
__device__ __forceinline__ double sembla_f64(unsigned long long bits) {
  return __longlong_as_double((long long)bits);
}
__device__ __forceinline__ long long sembla_total_key(double value) {
  long long bits = __double_as_longlong(value);
  return bits ^ (long long)(((unsigned long long)(bits >> 63)) >> 1);
}
__device__ __forceinline__ int sembla_total_less(double left, double right) {
  return sembla_total_key(left) < sembla_total_key(right);
}
__device__ __forceinline__ int sembla_total_equal(double left, double right) {
  return sembla_total_key(left) == sembla_total_key(right);
}
__device__ __forceinline__ long long sembla_add_i64(long long a, long long b, unsigned char* error) {
  if ((b > 0 && a > 0x7fffffffffffffffLL - b) ||
      (b < 0 && a < (-0x7fffffffffffffffLL - 1LL) - b)) { *error = 1; return 0; }
  return a + b;
}
__device__ __forceinline__ long long sembla_sub_i64(long long a, long long b, unsigned char* error) {
  if ((b < 0 && a > 0x7fffffffffffffffLL + b) ||
      (b > 0 && a < (-0x7fffffffffffffffLL - 1LL) + b)) { *error = 1; return 0; }
  return a - b;
}
__device__ __forceinline__ long long sembla_mul_i64(long long a, long long b, unsigned char* error) {
  const long long min = (-0x7fffffffffffffffLL - 1LL);
  const long long max = 0x7fffffffffffffffLL;
  if (a == 0 || b == 0) return 0;
  if ((a == min && b == -1) || (b == min && a == -1)) { *error = 1; return 0; }
  if (a > 0) {
    if ((b > 0 && a > max / b) || (b < 0 && b < min / a)) { *error = 1; return 0; }
  } else {
    if ((b > 0 && a < min / b) || (b < 0 && a < max / b)) { *error = 1; return 0; }
  }
  return a * b;
}
__device__ __forceinline__ void sembla_philox(unsigned int counter[4], unsigned int key[2]) {
  const unsigned int M0 = 0xD2511F53U, M1 = 0xCD9E8D57U;
  const unsigned int W0 = 0x9E3779B9U, W1 = 0xBB67AE85U;
  #pragma unroll
  for (int round = 0; round < 10; ++round) {
    unsigned long long p0 = (unsigned long long)M0 * counter[0];
    unsigned long long p1 = (unsigned long long)M1 * counter[2];
    unsigned int next0 = (unsigned int)(p1 >> 32) ^ counter[1] ^ key[0];
    unsigned int next1 = (unsigned int)p1;
    unsigned int next2 = (unsigned int)(p0 >> 32) ^ counter[3] ^ key[1];
    unsigned int next3 = (unsigned int)p0;
    counter[0] = next0; counter[1] = next1; counter[2] = next2; counter[3] = next3;
    if (round != 9) { key[0] += W0; key[1] += W1; }
  }
}
__device__ __forceinline__ double sembla_uniform(unsigned long long seed, unsigned int tick,
                                                  unsigned int rule, unsigned int entity,
                                                  unsigned int draw) {
  unsigned int counter[4] = {tick, rule, entity, draw};
  unsigned int key[2] = {(unsigned int)seed, (unsigned int)(seed >> 32)};
  sembla_philox(counter, key);
  unsigned long long mantissa = ((unsigned long long)counter[0] << 21) |
                                ((unsigned long long)counter[1] >> 11);
  double sample = ((double)mantissa + 0.5) * (1.0 / 9007199254740992.0);
  return sample == 1.0 ? sembla_f64(0x3fefffffffffffffULL) : sample;
}
__device__ __forceinline__ double sembla_exp(unsigned long long seed, unsigned int tick,
                                              unsigned int rule, unsigned int entity,
                                              unsigned int draw, double lambda) {
  return lambda <= 0.0 ? sembla_f64(0x7ff0000000000000ULL)
                       : -log(sembla_uniform(seed, tick, rule, entity, draw)) / lambda;
}

extern "C" __global__ void sembla_reset_status(unsigned long long* status, unsigned char* aggregate_errors, unsigned long long error_count) {
  if (blockIdx.x != 0 || threadIdx.x != 0) return;
  status[0] = 0ULL; status[1] = 0ULL; status[2] = 0ULL; status[3] = 0ULL;
  for (unsigned long long i = 0; i < error_count; ++i) aggregate_errors[i] = 0U;
}

extern "C" __global__ void sembla_mark_effect_aggregates(const unsigned long long* row_counts, const unsigned long long* candidate_offsets, const unsigned char* wins, unsigned char* active, unsigned long long aggregate_count) {
  if (blockIdx.x != 0 || threadIdx.x != 0) return;
  for (unsigned long long i = 0; i < aggregate_count; ++i) active[i] = 0U;
}

extern "C" __global__ void sembla_build_aggregate_partials(const unsigned char* state, const unsigned long long* column_offsets, const unsigned long long* row_counts, const unsigned char* inputs, const unsigned long long* input_offsets, const unsigned long long* input_counts, const unsigned char* params, const unsigned char* aggs, const unsigned char* aggregate_facts, unsigned int aggregate_index, const unsigned char* aggregate_active, unsigned char require_active, unsigned char* partials, const unsigned long long* agg_offsets, unsigned char* aggregate_errors) {
  unsigned int worker = blockIdx.x * blockDim.x + threadIdx.x;
  if (worker != 0U || (require_active && !aggregate_active[aggregate_index])) return;
  unsigned char local_error = 0; unsigned char* error = &local_error;
  if (aggregate_index == 0U) { unsigned long long group_count = row_counts[1]; long long* values = (long long*)(partials + agg_offsets[0] * 2ULL);
    for (unsigned long long group = 0; group < group_count; ++group) values[group] = (long long)0;
    for (unsigned long long row = 0; row < row_counts[0]; ++row) { local_error = 0; (void)((((*((const unsigned short*)(state + column_offsets[0]) + (unsigned long long)(row)))) == 1U)); if (local_error) { aggregate_errors[0] = 2U; return; } }
    for (unsigned long long row = 0; row < row_counts[0]; ++row) { local_error = 0; int selected = (((*((const unsigned short*)(state + column_offsets[0]) + (unsigned long long)(row)))) == 1U); if (local_error) { aggregate_errors[0] = 2U; return; }
      if (selected) { unsigned int group = (*((const unsigned int*)(state + column_offsets[1]) + (unsigned long long)(row))); if ((unsigned long long)group >= group_count) { aggregate_errors[0] = 1U; return; } values[group] = sembla_add_i64(values[group], 1LL, error); if (local_error) { aggregate_errors[0] = 2U; return; } }
    }
  }
  if (aggregate_index == 1U) { unsigned long long group_count = row_counts[1]; long long* values = (long long*)(partials + agg_offsets[1] * 2ULL);
    for (unsigned long long group = 0; group < group_count; ++group) values[group] = (long long)0;
    for (unsigned long long row = 0; row < row_counts[0]; ++row) { local_error = 0; (void)(1); if (local_error) { aggregate_errors[0] = 2U; return; } }
    for (unsigned long long row = 0; row < row_counts[0]; ++row) { local_error = 0; int selected = 1; if (local_error) { aggregate_errors[0] = 2U; return; }
      if (selected) { unsigned int group = (*((const unsigned int*)(state + column_offsets[1]) + (unsigned long long)(row))); if ((unsigned long long)group >= group_count) { aggregate_errors[0] = 1U; return; } values[group] = sembla_add_i64(values[group], 1LL, error); if (local_error) { aggregate_errors[0] = 2U; return; } }
    }
  }
}

extern "C" __global__ void sembla_finish_aggregates(const unsigned char* partials, const unsigned long long* row_counts, unsigned int aggregate_index, const unsigned char* aggregate_active, unsigned char require_active, unsigned char* aggs, const unsigned long long* agg_offsets, unsigned char* aggregate_errors) {
  unsigned long long group = (unsigned long long)blockIdx.x * blockDim.x + threadIdx.x;
  if (require_active && !aggregate_active[aggregate_index]) return;
  if (aggregate_index == 0U && group < row_counts[1]) { const long long* base = (const long long*)(partials + agg_offsets[0] * 2ULL); long long* result = (long long*)(aggs + agg_offsets[0]); result[group] = base[group]; }
  if (aggregate_index == 1U && group < row_counts[1]) { const long long* base = (const long long*)(partials + agg_offsets[1] * 2ULL); long long* result = (long long*)(aggs + agg_offsets[1]); result[group] = base[group]; }
}

extern "C" __global__ void sembla_record_aggregate_errors(unsigned char* errors, unsigned long long count, unsigned long long aggregate_index, unsigned char* aggregate_facts) {
  if (blockIdx.x != 0 || threadIdx.x != 0) return;
  unsigned char code = 0U;
  for (unsigned long long i = 0; i < count; ++i) { if (code == 0U && errors[i]) code = errors[i]; errors[i] = 0U; }
  aggregate_facts[aggregate_index] = code;
}

extern "C" __global__ void sembla_validate_transition(const unsigned char* state, const unsigned long long* column_offsets, const unsigned long long* row_counts, const unsigned char* inputs, const unsigned long long* input_offsets, const unsigned long long* input_counts, const unsigned char* params, const unsigned char* aggs, const unsigned char* aggregate_facts, const unsigned long long* agg_offsets, const unsigned long long* candidate_offsets, unsigned int rule_id, unsigned long long* status) {
  if (blockIdx.x != 0 || threadIdx.x != 0 || status[0] != 0ULL) return;
  unsigned char local_error = 0U; unsigned char* error = &local_error;
  if (rule_id == 0U) {
    if (aggregate_facts[0] != 0U) {
      status[0] = (unsigned long long)aggregate_facts[0]; status[1] = 0ULL; return;
    }
    if (aggregate_facts[1] != 0U) {
      status[0] = (unsigned long long)aggregate_facts[1]; status[1] = 1ULL; return;
    }
    return;
  }
  if (rule_id == 1U) {
    return;
  }
}

extern "C" __global__ void sembla_transition_00000000(const unsigned char* state, const unsigned long long* column_offsets, const unsigned long long* row_counts, const unsigned char* inputs, const unsigned long long* input_offsets, const unsigned long long* input_counts, const unsigned char* params, const unsigned char* aggs, const unsigned long long* agg_offsets, const unsigned long long* candidate_offsets, unsigned long long seed, unsigned int tick, double dt, unsigned char* enabled, double* times, unsigned char* errors, const unsigned long long* status) {
  unsigned long long row = (unsigned long long)blockIdx.x * blockDim.x + threadIdx.x;
  if (status[0] != 0ULL) return;
  if (row >= row_counts[0]) return;
  unsigned long long candidate = candidate_offsets[0] + row;
  unsigned char local_error = 0; unsigned char* error = &local_error;
  int guard = (((*((const unsigned short*)(state + column_offsets[0]) + (unsigned long long)(row)))) == 0U);
  errors[candidate * 2ULL] = local_error;
  local_error = 0;
  double lambda = (double)(([&]() { double sembla_left = (double)((*((const double*)(params + 0ULL)))); if (*error) return 0.0; double sembla_right = (double)(([&]() { double sembla_left = (double)((*((const long long*)(aggs + agg_offsets[0]) + (unsigned long long)((*((const unsigned int*)(state + column_offsets[1]) + (unsigned long long)(row))))))); if (*error) return 0.0; double sembla_right = (double)((*((const long long*)(aggs + agg_offsets[1]) + (unsigned long long)((*((const unsigned int*)(state + column_offsets[1]) + (unsigned long long)(row))))))); if (*error) return 0.0; return sembla_left / sembla_right; }())); if (*error) return 0.0; return sembla_left * sembla_right; }()));
  errors[candidate * 2ULL + 1ULL] = local_error;
  double time = sembla_exp(seed, tick, 0U, (unsigned int)row, 0U, lambda);
  times[candidate] = time;
  enabled[candidate] = (unsigned char)(errors[candidate * 2ULL] == 0U && errors[candidate * 2ULL + 1ULL] == 0U && guard && lambda > 0.0 && time < dt);
}

extern "C" __global__ void sembla_transition_00000001(const unsigned char* state, const unsigned long long* column_offsets, const unsigned long long* row_counts, const unsigned char* inputs, const unsigned long long* input_offsets, const unsigned long long* input_counts, const unsigned char* params, const unsigned char* aggs, const unsigned long long* agg_offsets, const unsigned long long* candidate_offsets, unsigned long long seed, unsigned int tick, double dt, unsigned char* enabled, double* times, unsigned char* errors, const unsigned long long* status) {
  unsigned long long row = (unsigned long long)blockIdx.x * blockDim.x + threadIdx.x;
  if (status[0] != 0ULL) return;
  if (row >= row_counts[0]) return;
  unsigned long long candidate = candidate_offsets[1] + row;
  unsigned char local_error = 0; unsigned char* error = &local_error;
  int guard = (((*((const unsigned short*)(state + column_offsets[0]) + (unsigned long long)(row)))) == 1U);
  errors[candidate * 2ULL] = local_error;
  local_error = 0;
  double lambda = (double)((*((const double*)(params + 8ULL))));
  errors[candidate * 2ULL + 1ULL] = local_error;
  double time = sembla_exp(seed, tick, 1U, (unsigned int)row, 0U, lambda);
  times[candidate] = time;
  enabled[candidate] = (unsigned char)(errors[candidate * 2ULL] == 0U && errors[candidate * 2ULL + 1ULL] == 0U && guard && lambda > 0.0 && time < dt);
}

extern "C" __global__ void sembla_check_candidate_errors(const unsigned char* errors, unsigned long long candidate_begin, unsigned long long candidate_count, unsigned long long* status) {
  if (blockIdx.x != 0 || threadIdx.x != 0 || status[0] != 0ULL) return;
  for (unsigned long long row = 0; row < candidate_count; ++row) { unsigned long long candidate = candidate_begin + row; if (errors[candidate * 2ULL]) { status[0] = 3ULL; status[1] = candidate; return; } }
  for (unsigned long long row = 0; row < candidate_count; ++row) { unsigned long long candidate = candidate_begin + row; if (errors[candidate * 2ULL + 1ULL]) { status[0] = 3ULL; status[1] = candidate; return; } }
}

extern "C" __global__ void sembla_validate_claims(const unsigned char* state, const unsigned long long* column_offsets, const unsigned long long* row_counts, const unsigned char* inputs, const unsigned long long* input_offsets, const unsigned long long* input_counts, const unsigned char* params, const unsigned char* aggs, const unsigned long long* agg_offsets, const unsigned long long* candidate_offsets, unsigned int rule_id, const unsigned char* enabled, unsigned long long* status) {
  if (blockIdx.x != 0 || threadIdx.x != 0 || status[0] != 0ULL) return;
  unsigned char local_error = 0; unsigned char* error = &local_error;
}

extern "C" __global__ void sembla_validate_claim_compatibility(const unsigned char* state, const unsigned long long* column_offsets, const unsigned long long* row_counts, const unsigned char* inputs, const unsigned long long* input_offsets, const unsigned long long* input_counts, const unsigned char* params, const unsigned char* aggs, const unsigned long long* agg_offsets, const unsigned long long* candidate_offsets, const unsigned char* enabled, unsigned int box_index, unsigned long long* status) {
  if (blockIdx.x != 0 || threadIdx.x != 0 || status[0] != 0ULL) return;
  unsigned char local_error = 0; unsigned char* error = &local_error;
}

extern "C" __global__ void sembla_resolve_conflicts(const unsigned char* state, const unsigned long long* column_offsets, const unsigned long long* row_counts, const unsigned char* inputs, const unsigned long long* input_offsets, const unsigned long long* input_counts, const unsigned char* params, const unsigned char* aggs, const unsigned long long* agg_offsets, const unsigned long long* candidate_offsets, unsigned long long candidate_begin, unsigned long long candidate_count, unsigned long long resource_table_count, const unsigned char* enabled, const double* times, unsigned char* wins, unsigned char* deferred, const unsigned long long* status) {
  unsigned long long local_candidate = (unsigned long long)blockIdx.x * blockDim.x + threadIdx.x;
  if (local_candidate >= candidate_count || status[0] != 0ULL) return;
  unsigned long long self_candidate = candidate_begin + local_candidate;
  for (unsigned long long table = 0; table < resource_table_count; ++table) deferred[self_candidate * resource_table_count + table] = 0U;
  wins[self_candidate] = enabled[self_candidate];
  if (!enabled[self_candidate]) return;
  unsigned char local_error = 0; unsigned char* error = &local_error;
}

extern "C" __global__ void sembla_validate_effects(const unsigned char* state, const unsigned long long* column_offsets, const unsigned long long* row_counts, const unsigned char* inputs, const unsigned long long* input_offsets, const unsigned long long* input_counts, const unsigned char* params, const unsigned char* aggs, const unsigned char* aggregate_facts, const unsigned long long* agg_offsets, const unsigned long long* candidate_offsets, const unsigned char* wins, unsigned int box_index, unsigned long long* status) {
  if (blockIdx.x != 0 || threadIdx.x != 0 || status[0] != 0ULL) return;
  unsigned char local_error = 0U; unsigned char* error = &local_error;
  if (box_index == 0U) { int any_winner = 0; for (unsigned long long row = 0; row < row_counts[0]; ++row) any_winner |= wins[candidate_offsets[0] + row] != 0; if (any_winner) {
    for (unsigned long long row = 0; row < row_counts[0]; ++row) { local_error = 0U; unsigned long long value = (unsigned long long)(1U); if (local_error) { status[0] = 5ULL; status[1] = candidate_offsets[0] + row; return; } if (value >= 3ULL) { status[0] = 6ULL; status[1] = candidate_offsets[0] + row; return; } }
  } }
  if (box_index == 0U) { int any_winner = 0; for (unsigned long long row = 0; row < row_counts[0]; ++row) any_winner |= wins[candidate_offsets[1] + row] != 0; if (any_winner) {
    for (unsigned long long row = 0; row < row_counts[0]; ++row) { local_error = 0U; unsigned long long value = (unsigned long long)(2U); if (local_error) { status[0] = 5ULL; status[1] = candidate_offsets[1] + row; return; } if (value >= 3ULL) { status[0] = 6ULL; status[1] = candidate_offsets[1] + row; return; } }
  } }
}

extern "C" __global__ void sembla_prepare_effects(const unsigned char* state, const unsigned long long* column_offsets, const unsigned long long* row_counts, const unsigned char* inputs, const unsigned long long* input_offsets, const unsigned long long* input_counts, const unsigned char* params, const unsigned char* aggs, const unsigned long long* agg_offsets, const unsigned long long* candidate_offsets, const unsigned char* wins, const unsigned long long* write_offsets, int* owners, unsigned long long* owner_values, unsigned long long owner_count, unsigned long long* status) {
  if (blockIdx.x != 0 || threadIdx.x != 0 || status[0] != 0ULL) return;
  for (unsigned long long i = 0; i < owner_count; ++i) owners[i] = -1;
  unsigned char local_error = 0; unsigned char* error = &local_error;
  { int any_winner = 0; for (unsigned long long row = 0; row < row_counts[0]; ++row) any_winner |= wins[candidate_offsets[0] + row] != 0; if (any_winner) {
    for (unsigned long long row = 0; row < row_counts[0]; ++row) { unsigned long long candidate = candidate_offsets[0] + row; if (!wins[candidate]) continue;
      {
      local_error = 0U; unsigned short value = (unsigned short)(1U); if (local_error) { status[0] = 5ULL; status[1] = candidate; return; }
      if ((unsigned long long)value >= 3ULL) { status[0] = 6ULL; status[1] = candidate; return; }
      { unsigned long long owner = write_offsets[0] + row; if (owners[owner] != -1) { status[0] = 8ULL; status[1] = owner; status[2] = (unsigned long long)owners[owner]; status[3] = 0ULL; return; } owners[owner] = (int)0U;
        owner_values[owner] = (unsigned long long)value;
      }
      }
    }
  }
  }
  { int any_winner = 0; for (unsigned long long row = 0; row < row_counts[0]; ++row) any_winner |= wins[candidate_offsets[1] + row] != 0; if (any_winner) {
    for (unsigned long long row = 0; row < row_counts[0]; ++row) { unsigned long long candidate = candidate_offsets[1] + row; if (!wins[candidate]) continue;
      {
      local_error = 0U; unsigned short value = (unsigned short)(2U); if (local_error) { status[0] = 5ULL; status[1] = candidate; return; }
      if ((unsigned long long)value >= 3ULL) { status[0] = 6ULL; status[1] = candidate; return; }
      { unsigned long long owner = write_offsets[0] + row; if (owners[owner] != -1) { status[0] = 8ULL; status[1] = owner; status[2] = (unsigned long long)owners[owner]; status[3] = 1ULL; return; } owners[owner] = (int)1U;
        owner_values[owner] = (unsigned long long)value;
      }
      }
    }
  }
  }
}

extern "C" __global__ void sembla_apply_effects(unsigned char* next_state, const unsigned long long* column_offsets, const unsigned long long* row_counts, const unsigned long long* write_offsets, const int* owners, const unsigned long long* owner_values, unsigned long long owner_count, const unsigned long long* status) {
  unsigned long long owner = (unsigned long long)blockIdx.x * blockDim.x + threadIdx.x;
  if (owner >= owner_count || status[0] != 0ULL || owners[owner] == -1) return;
  if (owner >= write_offsets[0] && owner < write_offsets[0] + row_counts[0]) { unsigned long long row = owner - write_offsets[0];
    *((unsigned short*)(next_state + column_offsets[0]) + row) = (unsigned short)owner_values[owner]; return; }
  if (owner >= write_offsets[1] && owner < write_offsets[1] + row_counts[0]) { unsigned long long row = owner - write_offsets[1];
    *((unsigned int*)(next_state + column_offsets[1]) + row) = (unsigned int)owner_values[owner]; return; }
}

extern "C" __global__ void sembla_validate_outputs(const unsigned char* state, const unsigned long long* column_offsets, const unsigned long long* row_counts, const unsigned char* inputs, const unsigned long long* input_offsets, const unsigned long long* input_counts, const unsigned char* params, const unsigned char* aggs, const unsigned char* aggregate_facts, const unsigned long long* agg_offsets, unsigned long long* status) {
  if (blockIdx.x != 0 || threadIdx.x != 0 || status[0] != 0ULL) return;
  unsigned char local_error = 0U; unsigned char* error = &local_error;
}

extern "C" __global__ void sembla_prepare_outputs(unsigned long long* next_input_counts, unsigned long long port_count, unsigned char* output_errors, unsigned long long error_count) {
  if (blockIdx.x != 0 || threadIdx.x != 0) return;
  for (unsigned long long i = 0; i < port_count; ++i) next_input_counts[i] = 0ULL;
  for (unsigned long long i = 0; i < error_count; ++i) output_errors[i] = 0U;
}

extern "C" __global__ void sembla_build_output_partials(const unsigned char* state, const unsigned long long* column_offsets, const unsigned long long* row_counts, const unsigned char* inputs, const unsigned long long* input_offsets, const unsigned long long* input_counts, const unsigned char* params, const unsigned char* aggs, const unsigned long long* agg_offsets, unsigned long long* output_partials, unsigned char* output_errors, const unsigned long long* status) {
  unsigned long long field = (unsigned long long)blockIdx.x * blockDim.x + threadIdx.x;
  if (status[0] != 0ULL) return;
  unsigned char local_error = 0; unsigned char* error = &local_error;
}

extern "C" __global__ void sembla_finish_outputs(const unsigned long long* output_partials, unsigned long long field_count, unsigned char* next_inputs, const unsigned long long* next_input_offsets, unsigned char* output_errors) {
  unsigned long long field = (unsigned long long)blockIdx.x * blockDim.x + threadIdx.x;
  if (field >= field_count) return;
}

extern "C" __global__ void sembla_check_output_errors(const unsigned char* errors, unsigned long long field_count, unsigned long long* status) {
  if (blockIdx.x != 0 || threadIdx.x != 0 || status[0] != 0ULL) return;
  for (unsigned long long field = 0; field < field_count; ++field) {
    if (errors[field]) { status[0] = 9ULL; status[1] = field; return; }
  }
}

extern "C" __global__ void sembla_philox_vectors(const unsigned long long* seeds,
                                                   const unsigned int* ticks,
                                                   const unsigned int* rules,
                                                   const unsigned int* entities,
                                                   const unsigned int* draws,
                                                   unsigned int* output,
                                                   unsigned int count) {
  unsigned int i = blockIdx.x * blockDim.x + threadIdx.x;
  if (i >= count) return;
  unsigned int counter[4] = {ticks[i], rules[i], entities[i], draws[i]};
  unsigned long long seed = seeds[i];
  unsigned int key[2] = {(unsigned int)seed, (unsigned int)(seed >> 32)};
  sembla_philox(counter, key);
  output[i * 4U + 0U] = counter[0];
  output[i * 4U + 1U] = counter[1];
  output[i * 4U + 2U] = counter[2];
  output[i * 4U + 3U] = counter[3];
}
