// Generated by sembla-cuda 0.3.0. DO NOT EDIT.
// model: sir_workplace_frequency_dependent

// No result-bearing atomics are used. State writes are sorted by generated
// rule/effect/row order and conflicts are resolved lexicographically.
__device__ __forceinline__ double sembla_f64(unsigned long long bits) {
  return __longlong_as_double((long long)bits);
}
__device__ __forceinline__ long long sembla_total_key(double value) {
  long long bits = __double_as_longlong(value);
  return bits ^ (long long)(((unsigned long long)(bits >> 63)) >> 1);
}
__device__ __forceinline__ int sembla_total_less(double left, double right) {
  return sembla_total_key(left) < sembla_total_key(right);
}
__device__ __forceinline__ int sembla_total_equal(double left, double right) {
  return sembla_total_key(left) == sembla_total_key(right);
}
__device__ __forceinline__ long long sembla_add_i64(long long a, long long b, unsigned char* error) {
  if ((b > 0 && a > 0x7fffffffffffffffLL - b) ||
      (b < 0 && a < (-0x7fffffffffffffffLL - 1LL) - b)) { *error = 1; return 0; }
  return a + b;
}
__device__ __forceinline__ long long sembla_sub_i64(long long a, long long b, unsigned char* error) {
  if ((b < 0 && a > 0x7fffffffffffffffLL + b) ||
      (b > 0 && a < (-0x7fffffffffffffffLL - 1LL) + b)) { *error = 1; return 0; }
  return a - b;
}
__device__ __forceinline__ long long sembla_mul_i64(long long a, long long b, unsigned char* error) {
  if (a == 0 || b == 0) return 0;
  if ((a == (-0x7fffffffffffffffLL - 1LL) && b == -1) ||
      (b == (-0x7fffffffffffffffLL - 1LL) && a == -1)) { *error = 1; return 0; }
  long long result = a * b;
  if (result / b != a) { *error = 1; return 0; }
  return result;
}
__device__ __forceinline__ void sembla_philox(unsigned int counter[4], unsigned int key[2]) {
  const unsigned int M0 = 0xD2511F53U, M1 = 0xCD9E8D57U;
  const unsigned int W0 = 0x9E3779B9U, W1 = 0xBB67AE85U;
  #pragma unroll
  for (int round = 0; round < 10; ++round) {
    unsigned long long p0 = (unsigned long long)M0 * counter[0];
    unsigned long long p1 = (unsigned long long)M1 * counter[2];
    unsigned int next0 = (unsigned int)(p1 >> 32) ^ counter[1] ^ key[0];
    unsigned int next1 = (unsigned int)p1;
    unsigned int next2 = (unsigned int)(p0 >> 32) ^ counter[3] ^ key[1];
    unsigned int next3 = (unsigned int)p0;
    counter[0] = next0; counter[1] = next1; counter[2] = next2; counter[3] = next3;
    if (round != 9) { key[0] += W0; key[1] += W1; }
  }
}
__device__ __forceinline__ double sembla_uniform(unsigned long long seed, unsigned int tick,
                                                  unsigned int rule, unsigned int entity,
                                                  unsigned int draw) {
  unsigned int counter[4] = {tick, rule, entity, draw};
  unsigned int key[2] = {(unsigned int)seed, (unsigned int)(seed >> 32)};
  sembla_philox(counter, key);
  unsigned long long mantissa = ((unsigned long long)counter[0] << 21) |
                                ((unsigned long long)counter[1] >> 11);
  double sample = ((double)mantissa + 0.5) * (1.0 / 9007199254740992.0);
  return sample == 1.0 ? sembla_f64(0x3fefffffffffffffULL) : sample;
}
__device__ __forceinline__ double sembla_exp(unsigned long long seed, unsigned int tick,
                                              unsigned int rule, unsigned int entity,
                                              unsigned int draw, double lambda) {
  return lambda <= 0.0 ? sembla_f64(0x7ff0000000000000ULL)
                       : -log(sembla_uniform(seed, tick, rule, entity, draw)) / lambda;
}

extern "C" __global__ void sembla_build_aggregates(const unsigned char* state, const unsigned long long* column_offsets, const unsigned long long* row_counts, const unsigned char* inputs, const unsigned long long* input_offsets, const unsigned long long* input_counts, const unsigned char* params, unsigned char* aggs, const unsigned long long* agg_offsets, unsigned long long* status) {
  if (blockIdx.x != 0 || threadIdx.x != 0) return;
  status[0] = 0ULL; status[1] = 0ULL; status[2] = 0ULL; status[3] = 0ULL;
  unsigned char local_error = 0; unsigned char* error = &local_error;
  long long* agg_0 = (long long*)(aggs + agg_offsets[0]);
  for (unsigned long long group = 0; group < row_counts[1]; ++group) agg_0[group] = (long long)0;
  for (unsigned long long row = 0; row < row_counts[0]; ++row) {
    if ((((*((const unsigned short*)(state + column_offsets[0]) + (unsigned long long)(row)))) == 1U)) { unsigned int group = (*((const unsigned int*)(state + column_offsets[1]) + (unsigned long long)(row))); if ((unsigned long long)group >= row_counts[1]) { status[0] = 1ULL; status[1] = 0ULL; return; }
      agg_0[group] = sembla_add_i64(agg_0[group], 1LL, error);
      if (local_error) { status[0] = 2ULL; status[1] = 0ULL; return; } }
  }
  long long* agg_1 = (long long*)(aggs + agg_offsets[1]);
  for (unsigned long long group = 0; group < row_counts[1]; ++group) agg_1[group] = (long long)0;
  for (unsigned long long row = 0; row < row_counts[0]; ++row) {
    if (1) { unsigned int group = (*((const unsigned int*)(state + column_offsets[1]) + (unsigned long long)(row))); if ((unsigned long long)group >= row_counts[1]) { status[0] = 1ULL; status[1] = 1ULL; return; }
      agg_1[group] = sembla_add_i64(agg_1[group], 1LL, error);
      if (local_error) { status[0] = 2ULL; status[1] = 1ULL; return; } }
  }
}

extern "C" __global__ void sembla_transition_00000000(const unsigned char* state, const unsigned long long* column_offsets, const unsigned long long* row_counts, const unsigned char* inputs, const unsigned long long* input_offsets, const unsigned long long* input_counts, const unsigned char* params, const unsigned char* aggs, const unsigned long long* agg_offsets, const unsigned long long* candidate_offsets, unsigned long long seed, unsigned int tick, double dt, unsigned char* enabled, double* times, unsigned char* errors) {
  unsigned long long row = (unsigned long long)blockIdx.x * blockDim.x + threadIdx.x;
  if (row >= row_counts[0]) return;
  unsigned long long candidate = candidate_offsets[0] + row;
  unsigned char local_error = 0; unsigned char* error = &local_error;
  int guard = (((*((const unsigned short*)(state + column_offsets[0]) + (unsigned long long)(row)))) == 0U);
  double lambda = (double)(((double)((*((const double*)(params + 0ULL)))) * (double)(((double)((*((const long long*)(aggs + agg_offsets[0]) + (unsigned long long)((*((const unsigned int*)(state + column_offsets[1]) + (unsigned long long)(row))))))) / (double)((*((const long long*)(aggs + agg_offsets[1]) + (unsigned long long)((*((const unsigned int*)(state + column_offsets[1]) + (unsigned long long)(row)))))))))));
  double time = sembla_exp(seed, tick, 0U, (unsigned int)row, 0U, lambda);
  errors[candidate] = local_error;
  times[candidate] = time;
  enabled[candidate] = (unsigned char)(!local_error && guard && lambda > 0.0 && time < dt);
}

extern "C" __global__ void sembla_transition_00000001(const unsigned char* state, const unsigned long long* column_offsets, const unsigned long long* row_counts, const unsigned char* inputs, const unsigned long long* input_offsets, const unsigned long long* input_counts, const unsigned char* params, const unsigned char* aggs, const unsigned long long* agg_offsets, const unsigned long long* candidate_offsets, unsigned long long seed, unsigned int tick, double dt, unsigned char* enabled, double* times, unsigned char* errors) {
  unsigned long long row = (unsigned long long)blockIdx.x * blockDim.x + threadIdx.x;
  if (row >= row_counts[0]) return;
  unsigned long long candidate = candidate_offsets[1] + row;
  unsigned char local_error = 0; unsigned char* error = &local_error;
  int guard = (((*((const unsigned short*)(state + column_offsets[0]) + (unsigned long long)(row)))) == 1U);
  double lambda = (double)((*((const double*)(params + 8ULL))));
  double time = sembla_exp(seed, tick, 1U, (unsigned int)row, 0U, lambda);
  errors[candidate] = local_error;
  times[candidate] = time;
  enabled[candidate] = (unsigned char)(!local_error && guard && lambda > 0.0 && time < dt);
}

extern "C" __global__ void sembla_check_candidate_errors(const unsigned char* errors, unsigned long long candidate_count, unsigned long long* status) {
  if (blockIdx.x != 0 || threadIdx.x != 0 || status[0] != 0ULL) return;
  for (unsigned long long i = 0; i < candidate_count; ++i) { if (errors[i]) { status[0] = 3ULL; status[1] = i; return; } }
}

extern "C" __global__ void sembla_resolve_conflicts(const unsigned char* state, const unsigned long long* column_offsets, const unsigned long long* row_counts, const unsigned char* inputs, const unsigned long long* input_offsets, const unsigned long long* input_counts, const unsigned char* params, const unsigned char* aggs, const unsigned long long* agg_offsets, const unsigned long long* candidate_offsets, unsigned long long candidate_count, const unsigned char* enabled, const double* times, unsigned char* wins, unsigned long long* status) {
  if (blockIdx.x != 0 || threadIdx.x != 0 || status[0] != 0ULL) return;
  for (unsigned long long i = 0; i < candidate_count; ++i) wins[i] = enabled[i];
  unsigned char local_error = 0; unsigned char* error = &local_error;
}

extern "C" __global__ void sembla_apply_effects(const unsigned char* state, unsigned char* next_state, const unsigned long long* column_offsets, const unsigned long long* row_counts, const unsigned char* inputs, const unsigned long long* input_offsets, const unsigned long long* input_counts, const unsigned char* params, const unsigned char* aggs, const unsigned long long* agg_offsets, const unsigned long long* candidate_offsets, const unsigned char* wins, const unsigned long long* write_offsets, int* owners, unsigned long long owner_count, unsigned long long* status) {
  if (blockIdx.x != 0 || threadIdx.x != 0 || status[0] != 0ULL) return;
  for (unsigned long long i = 0; i < owner_count; ++i) owners[i] = -1;
  unsigned char local_error = 0; unsigned char* error = &local_error;
  for (unsigned long long row = 0; row < row_counts[0]; ++row) { unsigned long long candidate = candidate_offsets[0] + row; if (!wins[candidate]) continue; local_error = 0; unsigned short value = (unsigned short )(1U); if (local_error) { status[0] = 5ULL; status[1] = candidate; return; }
    if ((unsigned long long)value >= 3ULL) { status[0] = 6ULL; status[1] = candidate; return; }
    unsigned long long owner = write_offsets[0] + row; if (owners[owner] != -1) { status[0] = 8ULL; status[1] = owner; status[2] = (unsigned long long)owners[owner]; status[3] = 0ULL; return; } owners[owner] = (int)0U; *((unsigned short*)(next_state + column_offsets[0]) + row) = value;
  }
  for (unsigned long long row = 0; row < row_counts[0]; ++row) { unsigned long long candidate = candidate_offsets[1] + row; if (!wins[candidate]) continue; local_error = 0; unsigned short value = (unsigned short )(2U); if (local_error) { status[0] = 5ULL; status[1] = candidate; return; }
    if ((unsigned long long)value >= 3ULL) { status[0] = 6ULL; status[1] = candidate; return; }
    unsigned long long owner = write_offsets[0] + row; if (owners[owner] != -1) { status[0] = 8ULL; status[1] = owner; status[2] = (unsigned long long)owners[owner]; status[3] = 1ULL; return; } owners[owner] = (int)1U; *((unsigned short*)(next_state + column_offsets[0]) + row) = value;
  }
}

extern "C" __global__ void sembla_build_outputs(const unsigned char* state, const unsigned long long* column_offsets, const unsigned long long* row_counts, const unsigned char* inputs, const unsigned long long* input_offsets, const unsigned long long* input_counts, const unsigned char* params, const unsigned char* aggs, const unsigned long long* agg_offsets, unsigned char* next_inputs, const unsigned long long* next_input_offsets, unsigned long long* next_input_counts, unsigned long long port_count, unsigned long long* status) {
  if (blockIdx.x != 0 || threadIdx.x != 0 || status[0] != 0ULL) return;
  for (unsigned long long i = 0; i < port_count; ++i) next_input_counts[i] = 0ULL;
  unsigned char local_error = 0; unsigned char* error = &local_error;
}

extern "C" __global__ void sembla_philox_vectors(const unsigned long long* seeds,
                                                   const unsigned int* ticks,
                                                   const unsigned int* rules,
                                                   const unsigned int* entities,
                                                   const unsigned int* draws,
                                                   unsigned int* output,
                                                   unsigned int count) {
  unsigned int i = blockIdx.x * blockDim.x + threadIdx.x;
  if (i >= count) return;
  unsigned int counter[4] = {ticks[i], rules[i], entities[i], draws[i]};
  unsigned long long seed = seeds[i];
  unsigned int key[2] = {(unsigned int)seed, (unsigned int)(seed >> 32)};
  sembla_philox(counter, key);
  output[i * 4U + 0U] = counter[0];
  output[i * 4U + 1U] = counter[1];
  output[i * 4U + 2U] = counter[2];
  output[i * 4U + 3U] = counter[3];
}
