#!/usr/bin/env bash
set -euo pipefail

if [[ "${SEMBLA_NPE_LOCK_CONTAINER:-}" != "1" ]]; then
  echo "error: run lock generation through ./scripts/check-npe-lock.sh" >&2
  exit 1
fi

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$root"

output="${1:-calibration/npe/requirements-ci.lock}"
case "$output" in
  /*) ;;
  *) output="$root/$output" ;;
esac

python - <<'PY'
import platform
import sys

expected = (3, 12, 8)
if sys.version_info[:3] != expected:
    raise SystemExit(
        f"error: lock generation requires CPython {expected[0]}.{expected[1]}.{expected[2]}, "
        f"found {platform.python_version()}"
    )
if platform.system() != "Linux" or platform.machine() != "x86_64":
    raise SystemExit(
        "error: lock generation requires Linux/x86_64, "
        f"found {platform.system()}/{platform.machine()}"
    )
PY

tmp="$(mktemp -d)"
staging=""
cleanup() {
  rm -rf "$tmp"
  if [[ -n "$staging" ]]; then
    rm -f "$staging"
  fi
}
trap cleanup EXIT

cat >"$tmp/uv-bootstrap.txt" <<'EOF'
uv==0.5.18 --hash=sha256:04e6c62d8947f62f1ec3255b5743cc775950b6203b06bf9c4d50682dcd68f340
EOF
python -m venv "$tmp/generator"
"$tmp/generator/bin/python" -m pip install \
  --disable-pip-version-check \
  --index-url https://pypi.org/simple \
  --only-binary=:all: \
  --no-deps \
  --require-hashes \
  -r "$tmp/uv-bootstrap.txt"

# nflows 0.14 is sdist-only. These exact build tools are part of the target
# environment so installation can disable PEP 517 build isolation without an
# unhashed bootstrap download.
cat >"$tmp/compile.in" <<EOF
-r $root/calibration/npe/requirements.txt
setuptools==75.8.0
wheel==0.45.1
EOF

"$tmp/generator/bin/uv" pip compile \
  --custom-compile-command "./scripts/check-npe-lock.sh" \
  --default-index https://pypi.org/simple \
  --emit-find-links \
  --emit-index-url \
  --exclude-newer 2026-07-23T00:00:00Z \
  --generate-hashes \
  --index-strategy first-index \
  --no-annotate \
  --no-header \
  --output-file "$tmp/uv.lock" \
  --python-platform x86_64-manylinux_2_17 \
  --python-version 3.12 \
  --quiet \
  "$tmp/compile.in"

# uv 0.5.18 does not emit hashes for artifacts selected from a flat
# --find-links page. The target-specific PyTorch wheel hash below was verified
# independently and is checked again by pip during the authoritative install.
python - "$tmp/uv.lock" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
text = path.read_text(encoding="utf-8")
needle = "torch==2.5.1+cpu\n"
replacement = (
    "torch==2.5.1+cpu \\\n"
    "    --hash=sha256:4856f9d6925121d13c2df07aa7580b767f449dfe71ae5acde9c27535d5da4840\n"
)
if text.count(needle) != 1:
    raise SystemExit(
        "error: expected exactly one unhashed torch==2.5.1+cpu entry from uv"
    )
path.write_text(text.replace(needle, replacement), encoding="utf-8")
PY

input_hash="$(python - <<'PY'
from hashlib import sha256
from pathlib import Path

print(sha256(Path("calibration/npe/requirements.txt").read_bytes()).hexdigest())
PY
)"
mkdir -p "$(dirname "$output")"
staging="$(mktemp "$(dirname "$output")/.requirements-ci.lock.tmp.XXXXXX")"
{
  cat <<EOF
# Generated by calibration/npe/generate-requirements-ci-lock.sh; do not edit.
# Target: Linux/amd64, CPython 3.12.8, manylinux_2_17.
# Container: python:3.12.8-slim-bookworm@sha256:8859bd6ca943079262c27e38b7119cdacede77c463139a15651dd340087a6cc9
# Generator: uv==0.5.18 (wheel sha256:04e6c62d8947f62f1ec3255b5743cc775950b6203b06bf9c4d50682dcd68f340).
# Input-SHA256: $input_hash
# Resolution-Cutoff: 2026-07-23T00:00:00Z
# Build-Prerequisites: setuptools==75.8.0, wheel==0.45.1.
# Source-Policy: PyPI index plus the torch-only PyTorch CPU find-links page; no extra index.
# Regenerate-and-validate: ./scripts/check-npe-lock.sh
#
EOF
  cat "$tmp/uv.lock"
} >"$staging"
mv "$staging" "$output"
staging=""
