import Sembla.Lumping

/-!
# Executable group-by lumping fixtures

These closed fixtures pin the specification-level counting plans from
`DESIGN.md` §7 using kernel `decide`. They test proof target 1a only and do not
bind the model to the deep-embedded IR evaluator; target 1b remains open as
stated in `docs/prds-proof-track/README.md`.

Implementation note: the imported plans use the requested `table[i]?` spelling,
so no indexing-spelling deviation was required.
-/

namespace Sembla
namespace LumpingTests

/-- Twelve-person worked fixture over employers 0, 1, and 2. -/
def fixture : List Lumping.Person :=
  [ { employer := 0, infectious := true }
  , { employer := 1, infectious := false }
  , { employer := 0, infectious := false }
  , { employer := 2, infectious := true }
  , { employer := 1, infectious := true }
  , { employer := 0, infectious := true }
  , { employer := 2, infectious := false }
  , { employer := 1, infectious := true }
  , { employer := 0, infectious := false }
  , { employer := 2, infectious := true }
  , { employer := 1, infectious := false }
  , { employer := 0, infectious := true }
  ]

-- Employer totals are 0 ↦ 3, 1 ↦ 2, and 2 ↦ 2.
example :
    (List.range fixture.length).map (Lumping.naiveCount fixture)
      = [3, 2, 3, 2, 2, 3, 2, 2, 3, 2, 2, 3] := by
  decide

example :
    (List.range fixture.length).map (Lumping.groupedCount fixture)
      = [3, 2, 3, 2, 2, 3, 2, 2, 3, 2, 2, 3] := by
  decide

example : Lumping.naiveCount fixture 12 = 0 := by
  decide

example : Lumping.groupedCount fixture 12 = 0 := by
  decide

/-- A 60-row, seven-employer fixture generated by the formulas used by the
Rust `group_by_count_matches_naive_quadratic_lumping_reference` test. -/
def rustTwin : List Lumping.Person :=
  (List.range 60).map fun row =>
    { employer := (row * 17 + row / 7 + 11) % 7
    , infectious := decide ((row * 29 + row / 5 + 3) % 11 < 4)
    }

-- Operational twin: crates/sembla-runtime/tests/eval.rs
-- `group_by_count_matches_naive_quadratic_lumping_reference`.
example :
    (List.range rustTwin.length).map (Lumping.naiveCount rustTwin)
      = (List.range rustTwin.length).map (Lumping.groupedCount rustTwin) := by
  decide

end LumpingTests
end Sembla
